set_property SRC_FILE_INFO {cfile:/home/wx/Documents/PCIe/pcie_phy_0_ex/pcie_phy_0_ex.gen/sources_1/ip/pcie_phy_0/ip_0/synth/pcie_phy_0_gt.xdc rfile:../pcie_phy_0_ex/pcie_phy_0_ex.gen/sources_1/ip/pcie_phy_0/ip_0/synth/pcie_phy_0_gt.xdc id:1 order:EARLY scoped_inst:inst/Uscale_gt.us_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie_phy_0_gt_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wx/Documents/PCIe/pcie_phy_0_ex/pcie_phy_0_ex.gen/sources_1/ip/pcie_phy_0/source/ip_pcie_phy.xdc rfile:../pcie_phy_0_ex/pcie_phy_0_ex.gen/sources_1/ip/pcie_phy_0/source/ip_pcie_phy.xdc id:2 order:EARLY scoped_inst:inst} [current_design]
current_instance inst/Uscale_gt.us_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie_phy_0_gt_i/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y7 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_nets {inst/Uscale_gt.us_gt_phy_wrapper/PHY_TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_nets {inst/Uscale_gt.us_gt_phy_wrapper/PHY_TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_nets {inst/Uscale_gt.us_gt_phy_wrapper/PHY_TXOUTCLKSEL[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_pclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_coreclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_coreclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_coreclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_userclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_userclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/phy_clk_i/bufg_gt_userclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie_phy_0_gt_i/inst/gen_gtwizard_gthe3_top.pcie_phy_0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie_phy_0_gt_i/inst/gen_gtwizard_gthe3_top.pcie_phy_0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie_phy_0_gt_i/inst/gen_gtwizard_gthe3_top.pcie_phy_0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/Uscale_gt.us_gt_phy_wrapper/gt_wizard.gtwizard_top_i/pcie_phy_0_gt_i/inst/gen_gtwizard_gthe3_top.pcie_phy_0_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]}]
